routes/user.js
[Trello ticket](https://trello.com/c/135Xa1L6)
Wiki page is updated as well
https://github.com/wildeastengineer/MKeepAPI/wiki/Password-recovery
=> [develop] Trello-135Xa1L6: Pass recover API sends email with redirect URL

controllers/project.js, models/account.js, models/auth/user.js, models/currency.js, models/project.js, models/transaction.js, models/widget.js
~~update existing controllers due to new updates in models~~
~~write controller for project creation, call this method in user creation~~
~~update migration script with adding remained entities~~
~~update wiki due to implemented models~~
To many changes should be done for one sing PR so it decided to split the task into several ones
=> [develop] Trello-B55eT8ET: Create Project model

controllers/currency.js, controllers/passRecovery.js, controllers/project.js, controllers/user.js, models/project.js, routes/project.js, routes/routes.js, utils/validation.js
=> [develop][REVIEW] Trello-D30QlImW: Project controller and routes

controllers/currency.js, routes/currency.js
- updated method in controller
- updated route
=> [develop][REVIEW] Trello-ps9aSdFL: Updated get all currencies methodes

libs/oauth2.js
`base64` -> `hex` for getting safe symbols in tokens
`32` -> `16` for shorter tokens
=> [REVIEW] [develop] Fix tokens generating

routes/project.js, routes/routes.js, server.js, utils/expressPlugins/errorHandler.js, utils/expressPlugins/methodNotAllowedErrorHandler.js, utils/expressPlugins/notFoundErrorHandler.js
[Trello-PDraWvOL](https://trello.com/c/PDraWvOL): Added error handling via express middleware
=> [develop][REVIEW] Trello-PDraWvOL: Added error handling via express middleware

controllers/currency.js, controllers/project.js, routes/currency.js, routes/project.js
- move update project currencies method to currency controller
- remove not used methods from currency controller
- update currency routes
[Trello-kG7aI4Yd: ](https://trello.com/c/kG7aI4Yd)Refactoring currency and project controllers
=> [develop][REVIEW] Trello-kG7aI4Yd: Refactoring currency and project controllers

migrations/201607250811_exchangeRateServiceCreation.js, models/exchangeRateService.js
[Trello-heBFnhms](https://trello.com/c/heBFnhms): Migration for exchange currency rate services
=> [develop] [REVIEW] Trello-heBFnhms: Migration for exchange currency rate services 

controllers/currency.js, controllers/exchangerateservice.js, package.json, routes/currency.js, utils/expressPlugins/errorHandler.js
[Trello-7IByLDvd](https://trello.com/c/7IByLDvd): Get currency rate
GET `'/currencies/exchange-rate/:serviceId'`
GET `/currencies/exchange-rate'`
=> [develop] Trello-7IByLDvd: Get currency rate

gulpfile.js, jsHintConfig.js, package.json
[Trello-TrRJnS0Q:](https://trello.com/c/iAhz5qxs)  JS Hint
----------------
=> [develop] Trello-TrRJnS0Q: JSHint

test/spec/unit/controllers/public/exchangerateserviceSpec.js
[Trello-NC1OSXi5](https://trello.com/c/NC1OSXi5): Fixed unti test
=> [develop] Trello-NC1OSXi5: Fixed unti test

src/controllers/user.js, src/routes/user.js
[Trello-5ydEsPBZ: ](https://trello.com/c/5ydEsPBZ) Return proper error code for "User already exists"
=> [develop] Trello-5ydEsPBZ: Return proper error code for "User already exists"

src/controllers/currency.js, src/controllers/project.js
[Trello-LhsBL6rC](https://trello.com/c/LhsBL6rC): Fix project currencies updating
=> [develop] Trello-LhsBL6rC. Fix project currencies updating

src/routes/project.js
[Trello-edE53Zbf:](https://trello.com/c/edE53Zbf) Remove "/update" from project currencies endpoint
=> [develop] Trello-edE53Zbf: Remove "/update" from project currencies endpoint

src/migrations/201701080811_updateCurrenciesList.js
[Trello-MfKoewMB](https://trello.com/c/MfKoewMB): Update global currencies data
=> [develop] [REVIEW] Trello-MfKoewMB. Update global currencies data

src/routes/user.js
[Trello-E6Nwedua:](https://trello.com/c/E6Nwedua) Fixed get user by id
=> [develop] Trello-E6Nwedua: Fixed get user by id

src/controllers/category.js, src/controllers/project.js, src/routes/project.js
[Trello-N8nCutXk:](https://trello.com/c/N8nCutXk) Categories CRUD: Update
=> [develop] Trello-N8nCutXk: Categories CRUD: Update

src/controllers/project.js, src/routes/project.js, test/spec/unit/controllers/public/exchangerateserviceSpec.js
[Trello-Sd17EyXx:](https://trello.com/c/Sd17EyXx) Set active project
Functionality:
When /api/project/:id is called -> that project id is set to user.activeProject
=> [develop] Trello-Sd17EyXx: Set active project

src/controllers/user.js, src/server.js
[Trello-qIvH9W5h:](https://trello.com/c/qIvH9W5h) Added better notFoundError handling
For some reason we didn't use mongoose notFoundErrorHandler globally. I added changes that allow to use it.
So if client is missing in the request you will get 404 error with Client is not found error
=> [develop] Trello-qIvH9W5h: Added better notFoundError handling

package.json, src/libs/oauth2.js, src/server.js
[Trello-qKwDZRvW](https://trello.com/c/qKwDZRvW): Reorganize work with cookies
=> [REVIEW] [develop] Trello-qKwDZRvW: Reorganize work with cookies

src/controllers/account.js, src/controllers/category.js, src/server.js
[Trello-7goHFwf6](https://trello.com/c/7goHFwf6) - "Updating project's list of sub documents
leads to updating only the first one in the list"
=> [develop]Trello-7goHFwf6: Fixed the bug
